spreaksheet:
	cp ../../spreadsheet-ecology-lesson/00-intro.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/01-format-data.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/02-common-mistakes.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/03-dates-as-data.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/04-quality-control.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/05-exporting-data.html ./spreadsheet-ecology-lesson/.
	cp ../../spreadsheet-ecology-lesson/06-data-formats-caveats.html ./spreadsheet-ecology-lesson/.
